query Product($id: ID) {
  product(id: $id) {
    id
    productId
    productName
    brand
    description
    items {
      itemId
      name
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          Price
          ListPrice
        }
      }
    }
  }
}
